### PR TITLE
Parallel implementation using multi-threading

### PR DESCRIPTION
**Pull request by rdbrackston**
I have implemented a working parallel version of runabc for ABC rejection and ABC SMC. Not yet implemented for model selection.
The option of whether to use a parallel implementation is available as a last keyword argument. Since the implementation is multi-threading, the number of threads available to Julia must be set prior to launching.

Happy to implement any more changes if required.

### CODE REVIEW

**Comment by marcjwilliams1** [comment]
Looks great, thanks a lot.

I think the tests are failing because you need a comma after "parameter_parallel" here in runtests.jl:
```julia
tests = ["sampling", "parameter", "parameter_parallel" "bayesfactor", "util"]
```

could you add that to make sure CI test pass?

**Comment by rdbrackston** [comment]
Ok, that bug is now fixed, and also another to make it compatible with the plot recipes.

It seems the 32 bit tests are failing on AppVeyor but I'm unsure if this is specific to my new code.

**Comment by marcjwilliams1** [comment]
Yeah I've also been getting that so it's not your code. I'm not sure what's causing it to be honest.

**Comment by marcjwilliams1** [comment]
@rdbrackston  just released a new version with the parallel implementation. 

If there's anything else you think could be added or modified let me know. I'm working on making the perturbation kernels more generic at the moment.

**Comment by rdbrackston** [comment]
Great, thanks for doing that and adding the details in README. I'll aim to mirror the parallel implementation over to the model selection algorithms as well at some point.

I'm currently interested in problems in which I need to compare probability distributions, so may implement some more distances beyond Kolmogorov–Smirnov.

**Comment by marcjwilliams1** [comment]
The [Distances.jl](https://github.com/JuliaStats/Distances.jl) package has quite a lot of distances implemented in case it's useful

**Pull request merged**
